/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import Entities.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rey
 */
public class TiendaMascotas extends javax.swing.JFrame {

   
    ArrayList<Animales> lAnimales;
     DefaultTableModel mdlTabla;
    
    
    /**
     * Creates new form TiendaMascotas
     */
    public TiendaMascotas() {
        initComponents();
        //ESTA ES UNA LISTA QUE RELACIONA TODOS LOS OBJETOS (TODOS LOS ANIMALES DE LA TIERNDA)
        this.lAnimales = new ArrayList<>();
        
         this.mdlTabla= (DefaultTableModel) this.jTable1.getModel();
         //CREACION DE 5 ANIMALES POR CADA TIPO, PARA METERLOS EN UNA LISTA QUE RELACIONE TODOS LOS ANIMALES DE LA TIENDA
    
    //5 TIPO PEZ
    Pez p1 = new Pez("PAN", "PEZ PAYASO", "COPO", "ROJO Y BLANCO", "10CM", "M", "PEZ");
    Pez p2 = new Pez("CONCENTRADO", "PEZ BETA", "RAYO", "AZUL", "10CM", "F", "PEZ");
    Pez p3 = new Pez("ALGAS", "PEZ DORADO", "COMPI", "NARANJA", "15CM", "M", "PEZ");
    Pez p4 = new Pez("CONCENTRADO", "TILAPIA DEL NILO", "SAUL", "AZUL-NEGRO", "9CM", "M", "PEZ");
    Pez p5 = new Pez("CONCENTRADO", "PEZ LUNA", "PITER", "GRIS", "11CM", "F", "PEZ");
    
    //5 TIPO AVE
    Ave a1 = new Ave("GUACAMAYO", "SEMILLAS", "COCO", "AZUL-AMARILLO", "45CM", "M", "AVE");
    Ave a2 = new Ave("PERICO", "CONCENTRADO", "COLUMBUS", "AMARILLO", "10CM", "M", "AVE");
    Ave a3 = new Ave("PERICO-AUSTRALIANO", "MIGAS-PAN", "TATO", "VERDE", "10CM", "M", "AVE");
    Ave a4 = new Ave("HALCON", "CARNE", "SASHA", "NEGRO", "45CM", "F", "AVE");
    Ave a5 = new Ave("COLIBRÍ", "POLEM", "MIKA", "ROJO", "7CM", "F", "AVE");
    
    //5 TIPO ROEDOR
    Roedor r1 = new Roedor("RATA BLANCA", "GENERAL", "TALIN", "BLANCA", "12CM", "F", "ROEDOR");
    Roedor r2 = new Roedor("CONEJO", "HIERVA", "PUGY", "CAFE", "40CM", "F", "ROEDOR");
    Roedor r3 = new Roedor("HAMSTER", "CONCENTRADO", "TITO", "NEGRO", "6CM", "M", "ROEDOR");
    Roedor r4 = new Roedor("RATA MONTES", "GENERAL", "LEO", "BLANCA", "12CM", "F", "ROEDOR");
    Roedor r5 = new Roedor("ZORRILO", "FRUTAS", "RET", "BLANCO-NEGRO", "50CM", "M", "ROEDOR");
    
    //5 tIPO REPTIL
    Reptil re1 = new Reptil("TORTUGA", "HIERVA", "LEO", "VERDE", "20CM", "M", "REPTIL");
    Reptil re2 = new Reptil("IGUANA", "GENERAL", "MARGARITA", "VERDE", "20CM", "M", "REPTIL");
    Reptil re3 = new Reptil("CAMALEON", "INSECTOS", "CGARM", "VERDE-NEGRO", "20CM", "M", "REPTIL");
    Reptil re4 = new Reptil("TORTUGA", "HIERVA", "LOMB", "VERDE", "20CM", "M", "REPTIL");
    Reptil re5 = new Reptil("TORTUGA", "HIERVA", "TITO", "VERDE", "20CM", "M", "REPTIL");
    
    //5 TIPO INSECTO
    Insecto i1 = new Insecto("TARANTULA", "GENERAL", "JORGE", "NEGRO", "25CM", "M", "INSECTO");
    Insecto i2 = new Insecto("GRILLO", "HIERVA", "LOMBARDO", "CAFE-NEGRO", "2CM", "F", "INSECTO");
    Insecto i3 = new Insecto("MATIZ RELIGIOSA", "GENERAL", "MIA", "VERDE", "8CM", "M", "INSECTO");
    Insecto i4 = new Insecto("TARANTULA", "GENERAL", "MATI", "CAFE", "12CM", "M", "INSECTO");
    Insecto i5 = new Insecto("ESCORPION", "INSECTOS", "KING", "NEGRO", "12CM", "M", "INSECTO");
    
    //LLENADO DE LA LISTA DE LA RELACION DE OBJETOS, UN OBJETO TIPO ANIMALES TIENE UN ANIMAL POR TIPO COMO PROPIEDAD
    this.lAnimales.add(new Animales(p1, a1, r1, re1, i1));
    this.lAnimales.add(new Animales(p2, a2, r2, re2, i2));
    this.lAnimales.add(new Animales(p3, a3, r3, re3, i3));
    this.lAnimales.add(new Animales(p4, a4, r4, re4, i4));
    this.lAnimales.add(new Animales(p5, a5, r5, re5, i5));//////
    }

    @Override
    public void layout() {
        super.layout(); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Mascota: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEZ", "AVE", "ROEDOR", "REPTIL", "INSECTO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "NOMBRE", "COLOR", "COMIDA", "TAMAÑO", "SEXO", "ESPECIE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MUESTRAS DE MASCOTAS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("T     I     E     N     D     A            D    E           M    A    S    C    O    T    A    S");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 408, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel3)
                    .addContainerGap(761, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        if (jComboBox1.getSelectedItem().toString().toLowerCase().equals("pez")) {
             this.mdlTabla.setRowCount(0);
            for (int i = 0; i < lAnimales.size(); i++) {
                String[] registro1 = { 
                this.lAnimales.get(i).getPez().getTipoPez(), this.lAnimales.get(i).getPez().getNombre(),
                this.lAnimales.get(i).getPez().getColor(), this.lAnimales.get(i).getPez().getAlimento(),
                this.lAnimales.get(i).getPez().getTamaño(), this.lAnimales.get(i).getPez().getGenero(), "PEZ"
            };
            this.mdlTabla.addRow(registro1);
            }
        } else if (jComboBox1.getSelectedItem().toString().toLowerCase().equals("ave")) {
            this.mdlTabla.setRowCount(0);
            for (int i = 0; i < lAnimales.size(); i++) {
                String[] registro2 = { 
                this.lAnimales.get(i).getAve().getTipoPajaro(), this.lAnimales.get(i).getAve().getNombre(),
                this.lAnimales.get(i).getAve().getColor(), this.lAnimales.get(i).getAve().getComida(),
                this.lAnimales.get(i).getAve().getTamaño(), this.lAnimales.get(i).getAve().getGenero(), "AVE"
            };
            this.mdlTabla.addRow(registro2);
            }
        } else if (jComboBox1.getSelectedItem().toString().toLowerCase().equals("roedor")) {
            this.mdlTabla.setRowCount(0);
            for (int i = 0; i < lAnimales.size(); i++) {
                String[] registro3 = { 
                this.lAnimales.get(i).getRoedor().getEspecieRoedor(), this.lAnimales.get(i).getRoedor().getNombre(),
                this.lAnimales.get(i).getRoedor().getColor(), this.lAnimales.get(i).getRoedor().getAlimento(),
                this.lAnimales.get(i).getRoedor().getTamaño(), this.lAnimales.get(i).getRoedor().getGenero(), "ROEDOR"
            };
            this.mdlTabla.addRow(registro3);
            }
        } else if (jComboBox1.getSelectedItem().toString().toLowerCase().equals("reptil")) {
            this.mdlTabla.setRowCount(0);
            for (int i = 0; i < lAnimales.size(); i++) {
                String[] registro4 = { 
                this.lAnimales.get(i).getReptil().getEspecieReptil(), this.lAnimales.get(i).getReptil().getNombre(),
                this.lAnimales.get(i).getReptil().getColor(), this.lAnimales.get(i).getReptil().getVenenoso(),
                this.lAnimales.get(i).getReptil().getTamaño(), this.lAnimales.get(i).getReptil().getGenero(), "REPTIL"
            };
            this.mdlTabla.addRow(registro4);
            }
        } else if (jComboBox1.getSelectedItem().toString().toLowerCase().equals("insecto")) {
            this.mdlTabla.setRowCount(0);
            for (int i = 0; i < lAnimales.size(); i++) {
                String[] registro5 = { 
                this.lAnimales.get(i).getInsecto().getEspecieInsecto(), this.lAnimales.get(i).getInsecto().getNombre(),
                this.lAnimales.get(i).getInsecto().getColor(), this.lAnimales.get(i).getInsecto().getVenenoso(),
                this.lAnimales.get(i).getInsecto().getTamaño(), this.lAnimales.get(i).getInsecto().getGenero(), "INSECTO"
            };
            this.mdlTabla.addRow(registro5);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaMascotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaMascotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
