/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.util.ArrayList;
import Entidades.*;
import com.sun.swing.internal.plaf.metal.resources.metal;

/**
 *
 * @author kjlme
 */
public class frmInscripcion extends javax.swing.JFrame {
   ArrayList<Facultades>lFacultades;
//    //LISTAS ESTATICAS
    
//    //LISTAS DE MATERIAS DE CADA CARRERA DE ING Y ARQUI
//    ArrayList<Materia>lMateriasDesarrolloS;
//    ArrayList<Materia>lMateriasSistemas;
//    ArrayList<Materia>lMateriasIndustrial;
//    ArrayList<Materia>lMateriasAgro;
//    ArrayList<Materia>lMateriasArqui;
    /**
     * Creates new form frmInscripcion
     */
    public frmInscripcion() {
        initComponents();
        this.lFacultades = new ArrayList<>();

        
        llenadoDeListasEstaticas();
        //Combo de facultades
         for (int i = 0; i < lFacultades.size(); i++) {
            comboFacultades.addItem(lFacultades.get(i).getNombreFacu());
        }
      
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboFacultades = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboCarreras = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre del Estudiante", "Carrera", "Cantidad/Materias", "Materias Inscritas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable4.getColumnModel().getColumn(4).setResizable(false);
            jTable4.getColumnModel().getColumn(4).setPreferredWidth(400);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Facultad de Ingeniería y Arquitectura", jPanel5);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre del Estudiante", "Carrera", "Cantidad/Materias", "Materias Inscritas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(0).setResizable(false);
            jTable5.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable5.getColumnModel().getColumn(1).setResizable(false);
            jTable5.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable5.getColumnModel().getColumn(2).setResizable(false);
            jTable5.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable5.getColumnModel().getColumn(3).setResizable(false);
            jTable5.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable5.getColumnModel().getColumn(4).setResizable(false);
            jTable5.getColumnModel().getColumn(4).setPreferredWidth(400);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Facultad de Ciencias y Humanidades", jPanel7);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre del Estudiante", "Carrera", "Cantidad/Materias", "Materias Inscritas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setResizable(false);
            jTable6.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable6.getColumnModel().getColumn(1).setResizable(false);
            jTable6.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable6.getColumnModel().getColumn(2).setResizable(false);
            jTable6.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable6.getColumnModel().getColumn(3).setResizable(false);
            jTable6.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable6.getColumnModel().getColumn(4).setResizable(false);
            jTable6.getColumnModel().getColumn(4).setPreferredWidth(400);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Facultad de Ciencias de la Salud", jPanel8);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre del Estudiante", "Carrera", "Cantidad/Materias", "Materias Inscritas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setResizable(false);
            jTable7.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable7.getColumnModel().getColumn(1).setResizable(false);
            jTable7.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable7.getColumnModel().getColumn(2).setResizable(false);
            jTable7.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable7.getColumnModel().getColumn(3).setResizable(false);
            jTable7.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable7.getColumnModel().getColumn(4).setResizable(false);
            jTable7.getColumnModel().getColumn(4).setPreferredWidth(400);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Facultad de Ciencias Empresariales ", jPanel6);

        jTabbedPane1.addTab("Admin", jTabbedPane2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("FACULTADES");

        comboFacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFacultadesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("CARRERAS");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLES/MATERIA"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Docente", "Horarios", "Aula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MATERIAS DISPONIBLES"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre/Materia", "UV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        jButton1.setText("Inscribir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(comboFacultades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCarreras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFacultades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inscripción", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void llenadoDeListasEstaticas(){
        //FACULTAD DE INGENIERIA Y ARQUITECTURA
        this.lFacultades.add(new Facultades("Facultad de Ingenieria y Arquitectura"));
        this.lFacultades.get(0).lCarreras= new ArrayList<>();
        
        //CARRERAS
        
        //Ing. Desarrollo de Software
        this.lFacultades.get(0).lCarreras.add(new Carrera("Ingenieria en Desarrollo de Software"));
        this.lFacultades.get(0).lCarreras.get(0).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(0).lCarreras.get(0).lMaterias.add(new Materia("021", "Desarrollo del Pensamiento Matematico Avanzado", 
                new Docente("Claudia", "del Aguila"), "C23"));
        this.lFacultades.get(0).lCarreras.get(0).lMaterias.add(new Materia("034", "Programacion Orientada a Objetos", 
                new Docente("Arturo", "de Leon"), "B45"));
        this.lFacultades.get(0).lCarreras.get(0).lMaterias.add(new Materia("027", "Manejo de Estructura de Datos", 
                new Docente("Carlos", "Martinez"), "C35"));
        this.lFacultades.get(0).lCarreras.get(0).lMaterias.add(new Materia("022", "Desarrollo del Pensamiento Teologico", 
                new Docente("Ernesto", "Grijalva"), "G22"));
        this.lFacultades.get(0).lCarreras.get(0).lMaterias.add(new Materia("030", "COnfiguracion de Redes Informaticas", 
                new Docente("Rafael", ""), "C31"));
        
        //Ing. en Sistemas
        this.lFacultades.get(0).lCarreras.add(new Carrera("Ingenieria en Sistemas Informaticos"));
        this.lFacultades.get(0).lCarreras.get(1).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(0).lCarreras.get(1).lMaterias.add(new Materia("132", "Estadistica", 
                new Docente("Steven", "Melara"), "C21"));
        this.lFacultades.get(0).lCarreras.get(1).lMaterias.add(new Materia("143", "Fisica I", 
                new Docente("Francisco", "Tejada"), "C32"));
        this.lFacultades.get(0).lCarreras.get(1).lMaterias.add(new Materia("135", "Tecnologias Web", 
                new Docente("Jefferson", "Guevara"), "B32"));
        this.lFacultades.get(0).lCarreras.get(1).lMaterias.add(new Materia("142", "Sistemas Operativos", 
                new Docente("Esmeralda", "Torres"), "A32"));
        this.lFacultades.get(0).lCarreras.get(1).lMaterias.add(new Materia("137", "Auditoria de Sistemas", 
                new Docente("Christopher", "Perez"), "C11"));
        
        //Ing. Industrial
        this.lFacultades.get(0).lCarreras.add(new Carrera("Ingenieria Industrial"));
        this.lFacultades.get(0).lCarreras.get(2).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(0).lCarreras.get(2).lMaterias.add(new Materia("342", "Ingenieria Economica", 
                new Docente("Felipe", "Zepeda"), "C33"));
        this.lFacultades.get(0).lCarreras.get(2).lMaterias.add(new Materia("349", "Mecanica de los Solidos III", 
                new Docente("Pedro", "Alvarez"), "C14"));
        this.lFacultades.get(0).lCarreras.get(2).lMaterias.add(new Materia("355", "Ingenieria de Metodos", 
                new Docente("Luisa", "Gutierrez"), "B21"));
        this.lFacultades.get(0).lCarreras.get(2).lMaterias.add(new Materia("344", "Higiene y Seguridad Industrial", 
                new Docente("Rodolfo", "España"), "C33"));
        this.lFacultades.get(0).lCarreras.get(2).lMaterias.add(new Materia("353", "Tecnologia Industrial I", 
                new Docente("Alba", "Medina"), "B39"));
        
        //Arquitectura
        this.lFacultades.get(0).lCarreras.add(new Carrera("Arquitectura"));
        this.lFacultades.get(0).lCarreras.get(3).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(0).lCarreras.get(3).lMaterias.add(new Materia("174", "Diseño Arquitectonico I", 
                new Docente("Ramon", "Fernandez"), "C22"));
        this.lFacultades.get(0).lCarreras.get(3).lMaterias.add(new Materia("180", "Taller de Maquetas", 
                new Docente("Patricia", "Escobar"), "C45"));
        this.lFacultades.get(0).lCarreras.get(3).lMaterias.add(new Materia("185", "Medio Ambiente", 
                new Docente("Andres", "Perez"), "C11"));
        this.lFacultades.get(0).lCarreras.get(3).lMaterias.add(new Materia("176", "Vivienda", 
                new Docente("Mauricio", "Nuñez"), "C33"));
        this.lFacultades.get(0).lCarreras.get(3).lMaterias.add(new Materia("171", "Urbanismo I", 
                 new Docente("Nuria", "Ayala"), "G13"));
        
        //Ing. Agronomica
        this.lFacultades.get(0).lCarreras.add(new Carrera("Inegnieria Agronomica"));
        this.lFacultades.get(0).lCarreras.get(4).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(0).lCarreras.get(4).lMaterias.add(new Materia("070", "Biología General", 
                new Docente("Yesenia", "Aguilar"), "H12"));
        this.lFacultades.get(0).lCarreras.get(4).lMaterias.add(new Materia("083", "Estadistica Aplicada", 
                new Docente("Jesus", "Portillo"), "G7"));
        this.lFacultades.get(0).lCarreras.get(4).lMaterias.add(new Materia("072", "Genetica General", 
                new Docente("Adriana", "Lopez"), "H32"));
        this.lFacultades.get(0).lCarreras.get(4).lMaterias.add(new Materia("077", "Cultivos Perennes", 
                new Docente("Alfonso", "Barillas"), "H17"));
        this.lFacultades.get(0).lCarreras.get(4).lMaterias.add(new Materia("085", "Bioquimica", 
                new Docente("Rafael", "Luna"), "C25"));
        
        //=================================================================================================================
        
        //FACULTAD DE CIENCIAS Y HUMANIDADES
        this.lFacultades.add(new Facultades("Facultad de Ciencias y Humanidades"));
        this.lFacultades.get(1).lCarreras = new ArrayList<>();
        
        //Lic. en Ciencias Juridicas
        this.lFacultades.get(1).lCarreras.add(new Carrera("Licenciatura en Ciencias Juridicas"));
        this.lFacultades.get(1).lCarreras.get(0).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(1).lCarreras.get(0).lMaterias.add(new Materia("122", "Derecho Tributario", 
                new Docente("Oscar", "Murillo"), "B21"));
        this.lFacultades.get(1).lCarreras.get(0).lMaterias.add(new Materia("131", "Derecho Civil II", 
                new Docente("Teresa", "Moran"), "B12"));
        this.lFacultades.get(1).lCarreras.get(0).lMaterias.add(new Materia("127", "Derecho Internacional", 
                new Docente("Michelle", "Anaya"), "B25"));
        this.lFacultades.get(1).lCarreras.get(0).lMaterias.add(new Materia("134", "Criminologia", 
                new Docente("Pablo", "Cortez"), "B33"));
        this.lFacultades.get(1).lCarreras.get(0).lMaterias.add(new Materia("128", "Derecho Agroambiental", 
                new Docente("Josue", "Sanchez"), "B25"));
        
        //lic. en Educacion Basica
        this.lFacultades.get(1).lCarreras.add(new Carrera("Licenciatura en Educacion Basica"));
        this.lFacultades.get(1).lCarreras.get(1).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(1).lCarreras.get(1).lMaterias.add(new Materia("144", "Educacion y Sociedad", 
                new Docente("Patricia", "Callado"), "B31"));
        this.lFacultades.get(1).lCarreras.get(1).lMaterias.add(new Materia("140", "Historia de El Salvador", 
                new Docente("Milena", "Estevez"), "B24"));
        this.lFacultades.get(1).lCarreras.get(1).lMaterias.add(new Materia("147", "Bilogia y Nutricion Humana", 
                new Docente("Mauricio", "Figueroa"), "B32"));
        this.lFacultades.get(1).lCarreras.get(1).lMaterias.add(new Materia("151", "Educacion Inclusiva", 
                new Docente("Luis", "Quinteros"), "B43"));
        this.lFacultades.get(1).lCarreras.get(1).lMaterias.add(new Materia("147", "Investigacion Educativa I", 
                new Docente("Karla", "Arevalos"), "B03"));
        
        //Lic. en Idioma Ingles
        this.lFacultades.get(1).lCarreras.add(new Carrera("Licenciatura en Idioma Ingles"));
        this.lFacultades.get(1).lCarreras.get(2).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(1).lCarreras.get(2).lMaterias.add(new Materia("090", "Gramatica", 
                new Docente("Luis", "Polanco"), "B13"));
        this.lFacultades.get(1).lCarreras.get(2).lMaterias.add(new Materia("091", "English Phonetics", 
                new Docente("Karina", "Alfaro"), "B05"));
        this.lFacultades.get(1).lCarreras.get(2).lMaterias.add(new Materia("092", "Semiotics", 
                new Docente("Fernando", "Chicas"), "B21"));
        this.lFacultades.get(1).lCarreras.get(2).lMaterias.add(new Materia("093", "English Literature", 
                new Docente("Paolo", "Osorio"), "B36"));
        this.lFacultades.get(1).lCarreras.get(2).lMaterias.add(new Materia("094", "Oratory and Protocol", 
                new Docente("Fernanda", "Pleitez"), "B16"));
        
        //Lic. en en Periodismo
        this.lFacultades.get(1).lCarreras.add(new Carrera("Licenciatura en Periodismo"));
        this.lFacultades.get(1).lCarreras.get(3).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(1).lCarreras.get(3).lMaterias.add(new Materia("040", "Fotografia", 
                new Docente("Johanna", "Padilla"), "B34"));
        this.lFacultades.get(1).lCarreras.get(3).lMaterias.add(new Materia("041", "Semiotica", 
                new Docente("Karen", "Lopez"), "B22"));
        this.lFacultades.get(1).lCarreras.get(3).lMaterias.add(new Materia("042", "Taller de Periodismo para Radio", 
                new Docente("Oscar", "Pacheco"), "B17"));
        this.lFacultades.get(1).lCarreras.get(3).lMaterias.add(new Materia("043", "Opinion Publica", 
                new Docente("Federico", "Linares"), "B28"));
        this.lFacultades.get(1).lCarreras.get(3).lMaterias.add(new Materia("044", "Comunicacion Politica", 
                new Docente("Melissa", "Torres"), "B12"));
        //=========================================================================================================================
        
        //Facultad ciencias empresariales(2)
        this.lFacultades.add(new Facultades("Facultad de Ciencias Empresariales"));
        this.lFacultades.get(2).lCarreras = new ArrayList<>();
        
        //Diseño Grafico(0)
        this.lFacultades.get(2).lCarreras.add(new Carrera("Diseño Grafico Publicitario"));
        this.lFacultades.get(2).lCarreras.get(0).lMaterias = new ArrayList<>();
        //Materias
        lFacultades.get(2).lCarreras.get(0).lMaterias.add(new Materia("0100", "Teoria de la Comunicacion", new Docente("Raul", "Medina"), "A25"));
        lFacultades.get(2).lCarreras.get(0).lMaterias.add(new Materia("0101", "Dibujo Humoristico Publicitario", new Docente("Rene", "Orellana"), "A35"));
        lFacultades.get(2).lCarreras.get(0).lMaterias.add(new Materia("0102", "Medios de Comunicacion", new Docente("Marlon", "Moran"), "B30"));
        lFacultades.get(2).lCarreras.get(0).lMaterias.add(new Materia("0103", "Empaques y Envases", new Docente("Sofia", "Galdamez"), "B46"));
        
        //Administracion de Empresas
        this.lFacultades.get(2).lCarreras.add(new Carrera("Administracion de Empresas"));
        this.lFacultades.get(2).lCarreras.get(1).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(2).lCarreras.get(1).lMaterias.add(new Materia("0200", "Contabilidad I", new Docente("Mario", "Rivera"), "A21"));
        this.lFacultades.get(2).lCarreras.get(1).lMaterias.add(new Materia("0201", "Matematica Financiera", new Docente("Rolando", "Moran"), "A21"));
        this.lFacultades.get(2).lCarreras.get(1).lMaterias.add(new Materia("0202", "Costeo Directo", new Docente("Jose", "Sandoval"), "A21"));
        this.lFacultades.get(2).lCarreras.get(1).lMaterias.add(new Materia("0203", "Gestion de Personal", new Docente("Marlene", "Gutierrez"), "A35"));
        this.lFacultades.get(2).lCarreras.get(1).lMaterias.add(new Materia("0204", "SIstemas Presupuestarios", new Docente("Juan", "Rivas"), "A35"));
        
        //Mercadeo
        this.lFacultades.get(2).lCarreras.add(new Carrera("Mercadeo"));
        this.lFacultades.get(2).lCarreras.get(2).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(2).lCarreras.get(2).lMaterias.add(new Materia("0300", "Introduccion a la Economia", new Docente("Josue", "Acosta"), "B30"));
        this.lFacultades.get(2).lCarreras.get(2).lMaterias.add(new Materia("0301", "Contabilidad de Costos", new Docente("Daniel", "Moran"), "B30"));
        this.lFacultades.get(2).lCarreras.get(2).lMaterias.add(new Materia("0302", "Mercadeo Directo Integrado", new Docente("David", "Galindo"), "B30"));
        this.lFacultades.get(2).lCarreras.get(2).lMaterias.add(new Materia("0303", "Relaciones Publicas", new Docente("Miguel", "Valle"), "B30"));
        this.lFacultades.get(2).lCarreras.get(2).lMaterias.add(new Materia("0304", "Ventas Internacionales", new Docente("Claudia", "Rivas"), "B30"));
        
        //Lic en sistemas Informaticos Administrativos
        this.lFacultades.get(2).lCarreras.add(new Carrera("Lic en sistemas Informaticos Administrativos"));
        this.lFacultades.get(2).lCarreras.get(3).lMaterias = new ArrayList<>();
        //Materias
        this.lFacultades.get(2).lCarreras.get(3).lMaterias.add(new Materia("0400", "Programacion a Objetos I", new Docente("Wilson", "Cordoba"), "A45"));
        this.lFacultades.get(2).lCarreras.get(3).lMaterias.add(new Materia("0401", "Gestion Financiera", new Docente("Alex", "Colocho"), "A45"));
        this.lFacultades.get(2).lCarreras.get(3).lMaterias.add(new Materia("0402", "Sistemas Organizacionales", new Docente("Andrea", "Bertrand"), "A45"));
        this.lFacultades.get(2).lCarreras.get(3).lMaterias.add(new Materia("0403", "Programacion en Web II", new Docente("Mario", "Galdamez"), "B45"));
        this.lFacultades.get(2).lCarreras.get(3).lMaterias.add(new Materia("0404", "Desarrollo de Software", new Docente("Pedro", "Carcamo"), "B45"));
        
        
        //Turismo
        lFacultades.get(2).lCarreras.add(new Carrera("Turismo"));
        lFacultades.get(2).lCarreras.get(4).lMaterias = new ArrayList<>();
        //Materias
        lFacultades.get(2).lCarreras.get(4).lMaterias.add(new Materia("0500", "Administracion Gastronomico", new Docente("Raul", "Olivares"), "A20"));
        lFacultades.get(2).lCarreras.get(4).lMaterias.add(new Materia("0501", "Relaciones Publicas y Eventos", new Docente("Carlos", "Amaya"), "A20"));
        lFacultades.get(2).lCarreras.get(4).lMaterias.add(new Materia("0502", "Gestion Hotelera", new Docente("Carolina", "Oliva"), "A20"));
        lFacultades.get(2).lCarreras.get(4).lMaterias.add(new Materia("0503", "Legislacion Turistica", new Docente("Christian", "Osorio"), "A20"));
        lFacultades.get(2).lCarreras.get(4).lMaterias.add(new Materia("0504", "Gestion de Riesgos", new Docente("Margarita", "Olivorio"), "A20"));
        
        //============================================================================================================================================
        
        //Facultad de enfermeria 
        this.lFacultades.add(new Facultades("Facultad de Enfermería"));
        this.lFacultades.get(3).lCarreras = new ArrayList<>();
        
        //Medicina
        lFacultades.get(3).lCarreras.add(new Carrera("Medicina"));
        lFacultades.get(3).lCarreras.get(0).lMaterias = new ArrayList<>();
        //Materias
        lFacultades.get(3).lCarreras.get(0).lMaterias.add(new Materia("0600", "Inmunologia", new Docente("Mariano", "Salazar"), "E21"));
        lFacultades.get(3).lCarreras.get(0).lMaterias.add(new Materia("0601", "Nutricion", new Docente("Jose", "Navarro"), "E21"));
        lFacultades.get(3).lCarreras.get(0).lMaterias.add(new Materia("0602", "Fisiopatologia", new Docente("Marina", "Hernandez"), "E21"));
        lFacultades.get(3).lCarreras.get(0).lMaterias.add(new Materia("0603", "Medicina I", new Docente("Coralia", "Villalobos"), "E21"));
        lFacultades.get(3).lCarreras.get(0).lMaterias.add(new Materia("0604", "Psicquiatria", new Docente("Ana", "Mendez"), "E21"));
        
        //Enfermeria
        lFacultades.get(3).lCarreras.add(new Carrera("Enfermeria"));
        lFacultades.get(3).lCarreras.get(1).lMaterias = new ArrayList<>();
        //Materias
        lFacultades.get(3).lCarreras.get(1).lMaterias.add(new Materia("0700", "Bioquimica Humana", new Docente("Vanessa", "Lopez"), "E20"));
        lFacultades.get(3).lCarreras.get(1).lMaterias.add(new Materia("0701", "Enfermeria en Salud Comunitaria I", new Docente("Gabriela", "Moran"), "E20"));
        lFacultades.get(3).lCarreras.get(1).lMaterias.add(new Materia("0702", "Enfermeria Quirurgica", new Docente("Gabriela", "Moran"), "E20"));
        lFacultades.get(3).lCarreras.get(1).lMaterias.add(new Materia("0703", "Etica Social", new Docente("Rodrigo", "Vizcarra"), "E20"));
        lFacultades.get(3).lCarreras.get(1).lMaterias.add(new Materia("0704", "Microbiologia y Parasitologia", new Docente("Mario", "Hernandez"), "E20"));
        
        
        
                
        
        
        
        
        

    }
    private void comboFacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFacultadesActionPerformed
       
    }//GEN-LAST:event_comboFacultadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInscripcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCarreras;
    private javax.swing.JComboBox<String> comboFacultades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    // End of variables declaration//GEN-END:variables
}
